---
title: "Gov 50 Final Project"
author: "Zoe Yu"
description: "Gender in political debates"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

Does gender impact the topics that presidential candidates, from the primaries to the Presidential Debates between each party nominee, choose to cover, and their stances on these topics? Using transcripts of debates from The Commission on Presidential Debates and UC Santa Barbara's The American Presidency Project, I plan to analyze how gender impacts issue agendas during debates. I hypothesize that female political candidates will tend to cover social issues, like women's rights, compared to economic issues at a higher rate than their male counterparts, as they seek to represent their female constituents and would likely bring up women's rights messaging to bolster their campaigns (e.g. Hillary Clinton in 2016). This pattern has been shown in academic literature such as Kim Fridkin Khan's study on gender messaging in U.S. Senate campaigns and Jason Trucotte's study on differences in gender across presidential debates. My variables in the dataset include several topics such as "abortion," "guns," and "healthcare," which I will classify as either an economic or social issue. Then, I will identify whether the speaker of the topic was male or female. My variables will be coded =0 for economic issue and =1 for social issue, which I would then compare across gender lines to see if economic or social issues arose at a greater proportion for female versus male candidates. I would analyze these variables at both the party primary and presidential debate scale. I would like to investigate if there are differences between these two scales, as well. When I analyze the transcripts to see if female candidates were more likely to speak on social issues during political debates, I should observe a positive correlation between female candidates and social issue topics if my hypothesis is supported.